services:
  - type: web
    name: inefablestore
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_PATH
        value: /var/data/inefablestore.db
      - key: SECRET_KEY
        generateValue: true
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
